---
title: "Lab 10"
author: "Echo Tang"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup

```{r}

library(RSQLite)
library(DBI)

# Initialize a temporary in memory database
con <- dbConnect(SQLite(), ":memory:")

# Download tables
actor <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/actor.csv")
rental <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/rental.csv")
customer <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/customer.csv")
payment <- read.csv("https://raw.githubusercontent.com/ivanceras/sakila/master/csv-sakila-db/payment_p2007_01.csv")

# Copy data.frames to database
dbWriteTable(con, "actor", actor)
dbWriteTable(con, "rental", rental)
dbWriteTable(con, "customer", customer)
dbWriteTable(con, "payment", payment)
```

```{sql, connection = con, output.var = "x1"}
PRAGMA table_info(actor)
```

## Exercise 1

```{sql, connection = con}
SELECT actor_id, first_name, last_name
FROM actor
ORDER by last_name, first_name
```

## Exercise 2

```{sql, connection = con}
SELECT actor_id, first_name, last_name
FROM actor
WHERE last_name IN ('WILLIAMS', 'DAVIS')
ORDER BY last_name

```

## Exercise 3

```{sql, connection = con}
SELECT DISTINCT customer_id, rental_date
FROM rental
WHERE date(rental_date) = '2005-07-05'

```

## Exercise 4

### Exercise 4.1

```{sql, connection = con}
SELECT *
FROM payment
WHERE amount IN (1.99, 7.99, 9.99)

```

### Exercise 4.2

```{sql, connection = con}
SELECT *
FROM payment
WHERE amount > 5
```

### Exercise 4.3

```{sql, connection = con}
SELECT *
FROM payment
WHERE amount > 5 AND amount < 8
```

## Exercise 5

```{sql, connection = con}
SELECT payment_id, amount, last_name, b.customer_id
FROM payment AS a
  INNER JOIN customer AS b
  ON a.customer_id = b.customer_id
WHERE last_name = "DAVIS"
```

## Exercise 6

### Exercise 6.1
```{sql, connection = con}
SELECT COUNT()
FROM rental
```

### Exercise 6.2
```{sql, connection = con}
SELECT customer_id, COUNT(customer_id) as count
FROM rental
GROUP BY customer_id

```


### Exercise 6.3
```{sql, connection = con}
SELECT customer_id, COUNT(customer_id) as count
FROM rental
GROUP BY customer_id
ORDER BY count DESC
```

### Exercise 6.4
```{sql, connection = con}
SELECT customer_id, COUNT(customer_id) AS count
FROM rental
GROUP BY customer_id
HAVING count >= 40
ORDER BY count DESC

```

## Exercise 7

### Exercise 7.1
```{sql, connection = con}
SELECT AVG(amount) as avg, SUM(amount) as sum, MIN(amount) as min, MAX(amount) as max
FROM payment

```

### Exercise 7.2
```{sql, connection = con}
SELECT customer_id, AVG(amount) as avg, SUM(amount) as sum, MIN(amount) as min, MAX(amount) as max
FROM payment
GROUP BY customer_id

```

### Exercise 7.3
```{sql, connection = con}
SELECT customer_id, AVG(amount) as avg, SUM(amount) as sum, MIN(amount) as min, MAX(amount) as max, COUNT(customer_id) as n
FROM payment
GROUP BY customer_id
HAVING n > 5

```

```{r}
dbDisconnect(con)
```

